import { TenderData } from '../types/tender';

export const DEFAULT_TENDER_DATA: TenderData = {
  tender_id: 'WB-2026-ICT-089',
  title: 'Procurement of National Healthcare Cloud Infrastructure & Disaster Recovery Systems',
  procuring_entity: 'Directorate General of Health Services (DGHS)',
  bidder: 'Apex Enterprise Solutions Ltd.',
  submission_deadline: '2026-10-30',
  requirements: [
    {
      id: 'req_01',
      order: 1,
      title_en: 'Valid Trade License',
      title_bn: 'বৈধ ট্রেড লাইসেন্স',
      mandatory: true,
      has_expiry: true,
    },
    {
      id: 'req_02',
      order: 2,
      title_en: 'Tax Clearance Certificate (TIN & Latest Return)',
      title_bn: 'আয়কর পরিশোধ সনদ (টিআইএন ও সর্বশেষ দাখিল)',
      mandatory: true,
      has_expiry: true,
    },
    {
      id: 'req_03',
      order: 3,
      title_en: 'VAT Registration Certificate (13-digit BIN)',
      title_bn: 'মূসক নিবন্ধন সনদ (১৩ ডিজিট বিন)',
      mandatory: true,
      has_expiry: false,
    },
    {
      id: 'req_04',
      order: 4,
      title_en: 'Certificate of Incorporation & Memorandum',
      title_bn: 'নিবন্ধন সনদ ও সংঘস্মারক',
      mandatory: true,
      has_expiry: false,
    },
    {
      id: 'req_05',
      order: 5,
      title_en: 'Audited Financial Statements (Last 3 Years)',
      title_bn: 'নিরীক্ষিত আর্থিক বিবরণী (বিগত ৩ বছর)',
      mandatory: true,
      has_expiry: false,
    },
    {
      id: 'req_06',
      order: 6,
      title_en: 'Bank Solvency & Credit Facility Certificate',
      title_bn: 'ব্যাংক সচ্ছলতা ও ঋণ সুবিধা সনদ',
      mandatory: true,
      has_expiry: true,
    },
    {
      id: 'req_07',
      order: 7,
      title_en: 'Relevant Similar Experience Certificates',
      title_bn: 'সংশ্লিষ্ট সমজাতীয় কাজের অভিজ্ঞতা সনদ',
      mandatory: true,
      has_expiry: false,
    },
    {
      id: 'req_08',
      order: 8,
      title_en: 'Manufacturer Authorization Form (MAF)',
      title_bn: 'প্রস্তুতকারকের অনুমোদন পত্র (এমএএফ)',
      mandatory: true,
      has_expiry: true,
    },
    {
      id: 'req_09',
      order: 9,
      title_en: 'ISO 27001 / ISO 9001 Quality Certification',
      title_bn: 'আইএসও ২৭০০১ / ৯০০১ মান সনদ',
      mandatory: false,
      has_expiry: true,
    },
    {
      id: 'req_10',
      order: 10,
      title_en: 'Litigation History & Non-Blacklisting Declaration',
      title_bn: 'মামলা মোকদ্দমার ইতিহাস ও ব্ল্যাকলিস্টমুক্ত ঘোষণা',
      mandatory: false,
      has_expiry: false,
    },
  ],
};

export const ALTERNATE_TENDER_DATA: TenderData = {
  tender_id: 'RHD-2026-BR-014',
  title: 'Construction of 4-Lane Pre-stressed Concrete Bridge & Approach Roads',
  procuring_entity: 'Roads and Highways Department (RHD), Ministry of Road Transport',
  bidder: 'National Engineering & Construction Consortium',
  submission_deadline: '2026-11-15',
  requirements: [
    {
      id: 'rhd_01',
      order: 1,
      title_en: 'Up-to-Date Contractor Enlistment License',
      title_bn: 'হালনাগাদ ঠিকাদার তালিকাভুক্তি লাইসেন্স',
      mandatory: true,
      has_expiry: true,
    },
    {
      id: 'rhd_02',
      order: 2,
      title_en: 'TIN & Income Tax Assessment Order',
      title_bn: 'টিআইএন ও আয়কর নির্ধারণী আদেশ',
      mandatory: true,
      has_expiry: true,
    },
    {
      id: 'rhd_03',
      order: 3,
      title_en: 'VAT Registration (BIN) Certificate',
      title_bn: 'মূসক নিবন্ধন সনদপত্র',
      mandatory: true,
      has_expiry: false,
    },
    {
      id: 'rhd_04',
      order: 4,
      title_en: 'Tender Security / Bid Bond Guarantee',
      title_bn: 'দরপত্র জামানত / বিড বন্ড গ্যারান্টি',
      mandatory: true,
      has_expiry: true,
    },
    {
      id: 'rhd_05',
      order: 5,
      title_en: 'Major Bridge Construction Experience Certificate',
      title_bn: 'প্রধান সেতু নির্মাণ অভিজ্ঞতা সনদপত্র',
      mandatory: true,
      has_expiry: false,
    },
    {
      id: 'rhd_06',
      order: 6,
      title_en: 'Key Personnel CVs & Engineering Certifications',
      title_bn: 'মূল প্রকৌশলীদের জীবনবৃত্তান্ত ও প্রত্যয়ন',
      mandatory: false,
      has_expiry: false,
    },
  ],
};
